### ISSUE TITLE
Gadget was installed but I don't see it's working!

### ISSUE THREAD

**Issue by mdkass** [sbrudz/gadget-hello-world#1]
Hello,
I succeeded to follow your demo steps and I see the gadget icon in Google apps icons, but when getting emails with "Hello Word" in the subject I don't see anything!!!

**Comment by sbrudz** [comment]
I was never able to get this working correctly.  It's close but because gadgets fail silently instead of displaying errors, I'm not sure what the problem is.  I tried again tonight but couldn't make any headway.  If you figure it out, a pull request would be welcome.

Instead of using a gadget, I ended up creating a Chrome extension.  The documentation is much better and it's more flexible.

I've put a warning notice at the top of the README to inform people that the steps listed don't fully work.

**Comment by mbf500** [comment]
Thanks for writing this walkthrough, sbrudz. It was very useful, but of course, I noticed the same issue described above.

Eventually, I got my gadget to appear by adding the following values:
Extractor param name: hello
Extractor param value: .*

I got these values from http://stackoverflow.com/questions/29926796/gmail-contextual-gadget. I don't know if it makes the gadget work for everyone, but I wanted to let you know.
